language: go

git:
  submodules: false

script:
  - mkdir $TRAVIS_BUILD_DIR/../../gravitational
  - ln -s $TRAVIS_BUILD_DIR $TRAVIS_BUILD_DIR/../../gravitational/teleport
  - ls -l $TRAVIS_BUILD_DIR/../../gravitational $TRAVIS_BUILD_DIR/../../gravitational/teleport
  - bash ./coverage.sh
go:
  - "1.11.x"
  - coverage