language: go

git:
  submodules: false

script:
  - apt install etcd
  - systemctl enable etcd
  - systemctl start etcd
  - mkdir $TRAVIS_BUILD_DIR/../../gravitational
  - ln -s $TRAVIS_BUILD_DIR $TRAVIS_BUILD_DIR/../../gravitational/teleport
  - ls -l $TRAVIS_BUILD_DIR/../../gravitational $TRAVIS_BUILD_DIR/../../gravitational/teleport
  - cd $TRAVIS_BUILD_DIR/../../gravitational/teleport
  - travis_wait 3600 bash ./coverage.sh
  - bash <(curl -s https://codecov.io/bash)
go:
  - "1.11.x"
  - coverage
